// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7mPFgdpjX0k2VRBnoftqMzzqdR2Vhdg',
    appId: '1:341947167820:web:a3ee55ab05d80c7654f0e9',
    messagingSenderId: '341947167820',
    projectId: 'appdata-f2a36',
    authDomain: 'appdata-f2a36.firebaseapp.com',
    storageBucket: 'appdata-f2a36.firebasestorage.app',
    measurementId: 'G-FK0QPZ1YBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzkVIkSRaYlSRK8DPN1Lc8_z_vs_CSMM',
    appId: '1:341947167820:android:21324e3c28e4eb3054f0e9',
    messagingSenderId: '341947167820',
    projectId: 'appdata-f2a36',
    storageBucket: 'appdata-f2a36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbG8pFi29Y7GVtBeEJ_vz-PAdNPBZ1jcg',
    appId: '1:341947167820:ios:390e6c0f12c0729f54f0e9',
    messagingSenderId: '341947167820',
    projectId: 'appdata-f2a36',
    storageBucket: 'appdata-f2a36.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbG8pFi29Y7GVtBeEJ_vz-PAdNPBZ1jcg',
    appId: '1:341947167820:ios:390e6c0f12c0729f54f0e9',
    messagingSenderId: '341947167820',
    projectId: 'appdata-f2a36',
    storageBucket: 'appdata-f2a36.firebasestorage.app',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI7mPFgdpjX0k2VRBnoftqMzzqdR2Vhdg',
    appId: '1:341947167820:web:852072929f576d9b54f0e9',
    messagingSenderId: '341947167820',
    projectId: 'appdata-f2a36',
    authDomain: 'appdata-f2a36.firebaseapp.com',
    storageBucket: 'appdata-f2a36.firebasestorage.app',
    measurementId: 'G-FY26T4GSNB',
  );
}
